export type {
  CreateFolderInput as CreateVaultFolderInput,
  CreateDocumentInput as CreateVaultDocumentInput,
  DocumentRecord as VaultDocument,
  DocumentSummary as VaultDocumentSummary,
  FolderNode as VaultFolderNode,
  MoveFolderInput as MoveVaultFolderInput,
  MoveDocumentInput as MoveVaultDocumentInput,
  RenameFolderInput as RenameVaultFolderInput,
  SaveDocumentInput as SaveVaultDocumentInput,
  WorkspaceSnapshot as VaultSnapshot,
} from '../domain/storage'
