export type {
  CreateDocumentInput as CreateVaultDocumentInput,
  DocumentRecord as VaultDocument,
  DocumentSummary as VaultDocumentSummary,
  FolderNode as VaultFolderNode,
  MoveDocumentInput as MoveVaultDocumentInput,
  SaveDocumentInput as SaveVaultDocumentInput,
  WorkspaceSnapshot as VaultSnapshot,
} from '../domain/storage'
